/**
 * @file config.js
 * @description Centralized configuration file for MeteoSwiss data visualization tools.
 * This file contains shared data like station information, parameter mappings,
 * and coordinate system definitions to ensure consistency across all tools.
 */

// A single global object is used to avoid polluting the global namespace.
const METEO_CONFIG = {

    /**
     * Initializes the coordinate system definitions required for Proj4js library.
     * This function should be called once when the application loads.
     * - EPSG:2056 is the Swiss CH1903+ / LV95 coordinate system.
     * - EPSG:4326 is the standard WGS84 system (latitude/longitude).
     */
    initializeProj4Defs: function() {
        if (typeof proj4 !== 'undefined') {
            proj4.defs('EPSG:2056', '+proj=somerc +lat_0=46.95240555555556 +lon_0=7.439583333333333 +k_0=1 +x_0=2600000 +y_0=1200000 +ellps=bessel +towgs84=674.374,15.056,405.346,0,0,0,0 +units=m +no_defs');
            proj4.defs('EPSG:4326', '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs');
        } else {
            // console.error('Proj4js library is not loaded. Coordinate transformations will fail.');
        }
    },

    /**
     * Contains all meteorological station data.
     * The object is keyed by the station's official abbreviation (e.g., 'LUG')
     * for easy and efficient data retrieval.
     */
    stations: {
        // --- Stazioni MeteoSvizzera ---
        'AIR': { name: 'Airolo', altitude: 1139, east: 2688910, north: 1153417, source: 'MeteoSvizzera', dataSource: 'ogd-smn-precip', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-niederschlag-temperatur&station=AIR' },
        'BIA': { name: 'Biasca', altitude: 278, east: 2718535, north: 1132792, source: 'MeteoSvizzera', dataSource: 'ogd-smn', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-automatisch&station=BIA' },
        'BLZ': { name: 'Bellinzona', altitude: 224, east: 2720913, north: 1116587, source: 'MeteoSvizzera', dataSource: 'ogd-smn-precip', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-niederschlag-temperatur&station=BLZ' },
        'BOS': { name: 'Bosco/Gurin', altitude: 1486, east: 2680880, north: 1130029, source: 'MeteoSvizzera', dataSource: 'ogd-smn-precip', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-niederschlag-temperatur&station=BOS' },
        'BRA': { name: 'Braggio', altitude: 1312, east: 2729967, north: 1128611, source: 'MeteoSvizzera', dataSource: 'ogd-nime', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-niederschlag-temperatur&station=BRA' },
        'BSG': { name: 'Brissago', altitude: 280, east: 2698199, north: 1108388, source: 'MeteoSvizzera', dataSource: 'ogd-nime', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-niederschlag-temperatur&station=BSG' },
        'CEV': { name: 'Cevio', altitude: 417, east: 2689688, north: 1130564, source: 'MeteoSvizzera', dataSource: 'ogd-smn', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-automatisch&station=CEV' },
        'CIM': { name: 'Cimetta', altitude: 1662, east: 2704434, north: 1117457, source: 'MeteoSvizzera', dataSource: 'ogd-smn', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-automatisch&station=CIM' },
        'CMD': { name: 'Camedo', altitude: 590, east: 2690295, north: 1112206, source: 'MeteoSvizzera', dataSource: 'ogd-nime', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-niederschlag-temperatur&station=CMD' },
        'COL': { name: 'Coldrerio', altitude: 347, east: 2721080, north: 1079234, source: 'MeteoSvizzera', dataSource: 'ogd-smn-precip', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-niederschlag-temperatur&station=COL' },
        'COM': { name: 'Acquarossa / Comprovasco', altitude: 575, east: 2714985, north: 1146451, source: 'MeteoSvizzera', dataSource: 'ogd-smn', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-automatisch&station=COM' },
        'CTO': { name: 'Torricella / Crana', altitude: 1002, east: 2712695, north: 1103745, source: 'MeteoSvizzera', dataSource: 'ogd-smn-precip', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-niederschlag-temperatur&station=CTO' },
        'FAI': { name: 'Faido', altitude: 747, east: 2704950, north: 1148266, source: 'MeteoSvizzera', dataSource: 'ogd-smn-precip', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-niederschlag-temperatur&station=FAI' },
        'GEN': { name: 'Monte Generoso', altitude: 1612, east: 2722503, north: 1087455, source: 'MeteoSvizzera', dataSource: 'ogd-smn', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-automatisch&station=GEN' },
        'GRO': { name: 'Grono', altitude: 382, east: 2733087, north: 1123512, source: 'MeteoSvizzera', dataSource: 'ogd-smn', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-automatisch&station=GRO' },
        'LUG': { name: 'Lugano', altitude: 273, east: 2717349, north: 1095908, source: 'MeteoSvizzera', dataSource: 'ogd-smn', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-automatisch&station=LUG' },
        'MAG': { name: 'Magadino / Cadenazzo', altitude: 204, east: 2711019, north: 1112215, source: 'MeteoSvizzera', dataSource: 'ogd-smn', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-automatisch&station=MAG' },
        'MOS': { name: 'Morbio Superiore', altitude: 594, east: 2723520, north: 1080124, source: 'MeteoSvizzera', dataSource: 'ogd-nime', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-niederschlag-temperatur&station=MOS' },
        'MSG': { name: 'Mosogno', altitude: 771, east: 2692802, north: 1117049, source: 'MeteoSvizzera', dataSource: 'ogd-smn-precip', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-niederschlag-temperatur&station=MSG' },
        'MTR': { name: 'Matro', altitude: 2172, east: 2714264, north: 1140943, source: 'MeteoSvizzera', dataSource: 'ogd-smn', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-automatisch&station=MTR' },
        'OLI': { name: 'Olivone', altitude: 890, east: 2714903, north: 1154143, source: 'MeteoSvizzera', dataSource: 'ogd-nime', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-niederschlag-temperatur&station=OLI' },
        'OTL': { name: 'Locarno / Monti', altitude: 367, east: 2704040, north: 1114447, source: 'MeteoSvizzera', dataSource: 'ogd-smn', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-automatisch&station=OTL' },
        'PIO': { name: 'Piotta', altitude: 1007, east: 2695079, north: 1150893, source: 'MeteoSvizzera', dataSource: 'ogd-smn', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-automatisch&station=PIO' },
        'POT': { name: 'Ponte Tresa', altitude: 274, east: 2710110, north: 1091628, source: 'MeteoSvizzera', dataSource: 'ogd-nime', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-niederschlag-temperatur&station=POT' },
        'ROE': { name: 'Robiei', altitude: 1898, east: 2682218, north: 1142981, source: 'MeteoSvizzera', dataSource: 'ogd-smn', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-automatisch&station=ROE' },
        'SBE': { name: 'San Bernardino', altitude: 1639, east: 2734116, north: 1147294, source: 'MeteoSvizzera', dataSource: 'ogd-smn', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-automatisch&station=SBE' },
        'SBO': { name: 'Stabio', altitude: 351, east: 2716049, north: 1077972, source: 'MeteoSvizzera', dataSource: 'ogd-smn', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-automatisch&station=SBO' },
        'SCD': { name: 'Scudellate', altitude: 920, east: 2724253, north: 1086841, source: 'MeteoSvizzera', dataSource: 'ogd-nime', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-niederschlag-temperatur&station=SCD' },
        'VIG': { name: 'Vira, Gambarogno', altitude: 225, east: 2709402, north: 1111548, source: 'MeteoSvizzera', dataSource: 'ogd-nime', url: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/valori-attuali-e-reti-di-misura.html#param=messnetz-niederschlag-temperatur&station=VIG' },

        // --- Stazioni OASI (INTEGRATE) ---
        'meteo_auto_621': { name: 'Airolo DT', altitude: 1157, east: 2690021, north: 1153641, source: 'OASI', startYear: 2016 },
        'meteo_auto_141': { name: 'Como ARPA', altitude: 201, east: 2726599, north: 1074948, source: 'OASI', startYear: 2000 },
        'meteo_auto_842': { name: 'Alpe di Neggia DT', altitude: 1395, east: 2708764, north: 1107528, source: 'OASI', startYear: 2019 },
        'meteo_auto_149': { name: 'Arcisate ARPA', altitude: 383, east: 2712824, north: 1078131, source: 'OASI', startYear: 2000 },
        'meteo_u_130': { name: 'Arosio DT', altitude: 860, east: 2713130, north: 1100610, source: 'OASI', startYear: 1987 },
        'meteo_auto_185': { name: 'Baceno Alpe Devero (ARPA)', altitude: 1634, east: 2663344, north: 1129990, source: 'OASI', startYear: 1991 },
        'meteo_u_70': { name: 'Bedretto DT', altitude: 1390, east: 2682250, north: 1151020, source: 'OASI', startYear: 1982 },
        'meteo_auto_221': { name: 'Biasca DT', altitude: 293, east: 2717000, north: 1135125, source: 'OASI', startYear: 2011 },
        'meteo_u_122': { name: 'Biasca - Val Pontirone DT', altitude: 1405, east: 2723875, north: 1137863, source: 'OASI', startYear: 2008 },
        'meteo_3': { name: 'Bioggio DT', altitude: 285, east: 2714170, north: 1096525, source: 'OASI', startYear: 1992 },
        'meteo_auto_463': { name: 'Cabbio DT', altitude: 612, east: 2724643, north: 1084028, source: 'OASI', startYear: 2014 },
        'meteo_u_126': { name: 'Camedo DT', altitude: 570, east: 2690050, north: 1112110, source: 'OASI', startYear: 1979 },
        'meteo_1': { name: 'Camignolo DT', altitude: 435, east: 2715430, north: 1106905, source: 'OASI', startYear: 2002 },
        'meteo_u_77': { name: 'Campo Valle Maggia DT', altitude: 1307, east: 2681717, north: 1126806, source: 'OASI', startYear: 2002 },
        'meteo_u_75': { name: 'Carena DT', altitude: 960, east: 2727220, north: 1114228, source: 'OASI', startYear: 2005 },
        'meteo_auto_142': { name: 'Cavargna ARPA', altitude: 1100, east: 2729353, north: 1105751, source: 'OASI', startYear: 2000 },
        'meteo_u_121': { name: 'Cavergno DT', altitude: 450, east: 2690100, north: 1133070, source: 'OASI', startYear: 2004 },
        'auto_52': { name: 'Ceresio Castagnola DT', altitude: 271, east: 2719433, north: 1095361, source: 'OASI', startYear: 2024 },
        'auto_58': { name: 'Chironico WSL', altitude: 1479, east: 2706013, north: 1144215, source: 'OASI', startYear: 2000 },
        'meteo_auto_161': { name: 'Chironico Cala DT', altitude: 1460, east: 2705195, north: 1141435, source: 'OASI', startYear: 2010 },
        'meteo_u_78': { name: 'Colla DT', altitude: 1020, east: 2725000, north: 1106400, source: 'OASI', startYear: 2006 },
        'auto_60': { name: 'Dalpe Alpe Géra DT', altitude: 1396, east: 2702386, north: 1145932, source: 'OASI', startYear: 2024 },
        'meteo_u_74': { name: 'Diga Luzzone DT', altitude: 1617, east: 2716690, north: 1158210, source: 'OASI', startYear: 1994 },
        'meteo_u_128': { name: 'Fusio DT', altitude: 1300, east: 2694090, north: 1144380, source: 'OASI', startYear: 1979 },
        'meteo_auto_101': { name: 'Giubiasco DT', altitude: 221, east: 2720231, north: 1114557, source: 'OASI', startYear: 2009 },
        'meteo_u_123': { name: 'Giubiasco IDA', altitude: 215, east: 2719130, north: 1114800, source: 'OASI', startYear: 1988 },
        'meteo_u_124': { name: 'Gnosca DT', altitude: 247, east: 2721940, north: 1121960, source: 'OASI', startYear: 1979 },
        'meteo_auto_183': { name: 'Grancia DT', altitude: 310, east: 2715262, north: 1092566, source: 'OASI', startYear: 2006 },
        'meteo_u_79': { name: 'Isone DT', altitude: 810, east: 2720180, north: 1110320, source: 'OASI', startYear: 1979 },
        'meteo_auto_154': { name: 'Lago Truzzo S. Giacomo ARPA', altitude: 2064, east: 2744807, north: 1136010, source: 'OASI', startYear: 2000 },
        'meteo_auto_146': { name: 'Lavena Ponte Tresa ARPA', altitude: 279, east: 2710314, north: 1091714, source: 'OASI', startYear: 2000 },
        'meteo_auto_661': { name: 'Lavertezzo Aquino DT', altitude: 635, east: 2707124, north: 1124609, source: 'OASI', startYear: 2017 },
        'meteo_auto_147': { name: 'Luino ARPA', altitude: 205, east: 2701193, north: 1094821, source: 'OASI', startYear: 2000 },
        'meteo_u_127': { name: 'Maggia DT', altitude: 327, east: 2697620, north: 1122190, source: 'OASI', startYear: 1984 },
        'meteo_u_132': { name: 'Mendrisio DT', altitude: 290, east: 2719210, north: 1083000, source: 'OASI', startYear: 1983 },
        'meteo_2': { name: 'Moleno DT', altitude: 255, east: 2719940, north: 1126560, source: 'OASI', startYear: 2002 },
        'auto_57': { name: 'Novaggio WSL', altitude: 1074, east: 2708158, north: 1097952, source: 'OASI', startYear: 1996 },
        'meteo_u_76': { name: 'Novaggio DT', altitude: 620, east: 2709980, north: 1096160, source: 'OASI', startYear: 2005 },
        'meteo_auto_966': { name: 'Novazzano DT', altitude: 248, east: 2721165, north: 1077152, source: 'OASI', startYear: 2021 },
        'meteo_u_129': { name: 'Olivone DT', altitude: 930, east: 2715410, north: 1154120, source: 'OASI', startYear: 1979 },
        'auto_65': { name: 'Lumino Parusciana DT', altitude: 1265, east: 2724674, north: 1122519, source: 'OASI', startYear: 2025 },
        'meteo_auto_641': { name: 'Piora Alpe DT', altitude: 1960, east: 2697970, north: 1155860, source: 'OASI', startYear: 2016 },
        'meteo_auto_148': { name: 'Poggio S. Elsa ARPA', altitude: 951, east: 2693663, north: 1084817, source: 'OASI', startYear: 2000 },
        'meteo_auto_143': { name: 'Porlezza ARPA', altitude: 287, east: 2731760, north: 1099891, source: 'OASI', startYear: 2000 },
        'meteo_auto_1030': { name: 'Preonzo Alpe Roscioro DT', altitude: 1518, east: 2719072, north: 1123304, source: 'OASI', startYear: 2022 },
        'meteo_auto_162': { name: 'Sonogno DT', altitude: 913, east: 2703633, north: 1133902, source: 'OASI', startYear: 2010 },
        'meteo_auto_926': { name: 'Sonvico DT', altitude: 578, east: 2719576, north: 1102086, source: 'OASI', startYear: 2021 },
        'auto_53': { name: 'Verbano Porto Ronco DT', altitude: 193, east: 2699847, north: 1111080, source: 'OASI', startYear: 2024 }
    },
    parameterMap: {
		'dkl010d0': { name: 'Direzione del vento;  media giornaliera', unit: '°' },
		'dkl010h0': { name: 'Direzione del vento;  media oraria', unit: '°' },
		'dkl010z0': { name: 'Direzione del vento;  media su 10\'', unit: '°' },
		'erefaod0': { name: 'Evaporazione referenze di FAO;  somma giornaliera', unit: 'mm/d' },
		'erefaoh0': { name: 'Evaporazione referenze di FAO;  somma oraria', unit: 'mm/h' },
		'erefaom0': { name: 'Evaporazione referenze di FAO;  somma mensile', unit: 'mm/d' },
		'erefaoy0': { name: 'Evaporazione referenze di FAO;  somma annuale', unit: 'mm/d' },
		'fkl010d0': { name: 'Velocità del vento scalare;  media giornaliera in m/s', unit: 'm/s' },
		'fkl010d1': { name: 'Raffica del vento (su un secondo);  massima giornaliera in m/s', unit: 'm/s' },
		'fkl010d3': { name: 'Raffica del vento (su tre secondi);  massima giornaliera in m/s', unit: 'm/s' },
		'fkl010h0': { name: 'Velocità del vento scalare;  media oraria in m/s', unit: 'm/s' },
		'fkl010h1': { name: 'Raffica del vento (su un secondo);  massima oraria in m/s', unit: 'm/s' },
		'fkl010h3': { name: 'Raffica del vento (su tre secondi);  massima oraria in m/s', unit: 'm/s' },
		'fkl010m0': { name: 'Velocità del vento scalare;  media mensile in m/s', unit: 'm/s' },
		'fkl010m1': { name: 'Raffica del vento (su un secondo);  massima mensile in m/s', unit: 'm/s' },
		'fkl010mn': { name: 'Velocità del vento scalare;  minima mensile in m/s', unit: 'm/s' },
		'fkl010mx': { name: 'Velocità del vento scalare;  massima mensile in m/s', unit: 'm/s' },
		'fkl010y0': { name: 'Velocità del vento scalare;  media annuale in m/s', unit: 'm/s' },
		'fkl010y1': { name: 'Raffica del vento (su un secondo);  massima annuale in m/s', unit: 'm/s' },
		'fkl010yn': { name: 'Velocità del vento scalare;  minima annuale in m/s', unit: 'm/s' },
		'fkl010yx': { name: 'Velocità del vento scalare;  massima annuale in m/s', unit: 'm/s' },
		'fkl010z0': { name: 'Velocità del vento scalare;  media su 10\' in m/s', unit: 'm/s' },
		'fkl010z1': { name: 'Raffica del vento (su un secondo);  massima su 10\' in m/s', unit: 'm/s' },
		'fkl010z3': { name: 'Raffica del vento (su tre secondi);  massima su 10\' in m/s', unit: 'm/s' },
		'fsk132d0': { name: 'Velocità del vento vettoriale;  media giornaliera', unit: 'm/s' },
		'fsk132h0': { name: 'Velocità del vento vettoriale;  media oraria', unit: 'm/s' },
		'fsk132z0': { name: 'Velocità del vento vettoriale;  media su 10\'', unit: 'm/s' },
		'fss132d0': { name: 'Velocità del vento;  deviazione standard giornaliera', unit: 'm/s' },
		'fss132h0': { name: 'Velocità del vento;  deviazione standard oraria', unit: 'm/s' },
		'fss132z0': { name: 'Velocità del vento;  deviazione standard su 10\'', unit: 'm/s' },
		'fu3010d0': { name: 'Velocità del vento scalare;  media giornaliera in km/h', unit: 'km/h' },
		'fu3010d1': { name: 'Raffica del vento (su un secondo);  massima giornaliera in km/h', unit: 'km/h' },
		'fu3010d3': { name: 'Raffica del vento (su tre secondi);  massima giornaliera in km/h', unit: 'km/h' },
		'fu3010h0': { name: 'Velocità del vento scalare;  media oraria in km/h', unit: 'km/h' },
		'fu3010h1': { name: 'Raffica del vento (su un secondo);  massima oraria in km/h', unit: 'km/h' },
		'fu3010h3': { name: 'Raffica del vento (su tre secondi);  massima oraria in km/h', unit: 'km/h' },
		'fu3010m0': { name: 'Velocità del vento scalare;  media mensile in km/h', unit: 'km/h' },
		'fu3010m1': { name: 'Raffica del vento (su un secondo);  massima mensile in km/h', unit: 'km/h' },
		'fu3010y0': { name: 'Velocità del vento scalare;  media annuale in km/h', unit: 'km/h' },
		'fu3010y1': { name: 'Raffica del vento (su un secondo);  massima annuale in km/h', unit: 'km/h' },
		'fu3010z0': { name: 'Velocità del vento;  media su 10\' in km/h', unit: 'km/h' },
		'fu3010z1': { name: 'Raffica del vento (su un secondo);  massima in km/h', unit: 'km/h' },
		'fu3010z3': { name: 'Raffica del vento (su tre secondi);  massima in km/h', unit: 'km/h' },
		'fv3010d0': { name: 'Componente V del vento;  media giornaliera', unit: 'm/s' },
		'fv3010h0': { name: 'Componente V del vento;  media oraria', unit: 'm/s' },
		'fv3010z0': { name: 'Componente V del vento;  media su 10\'', unit: 'm/s' },
		'fve010h0': { name: 'Velocità del vento vettoriale;  media oraria in m/s', unit: 'm/s' },
		'fve010z0': { name: 'Velocità del vento vettoriale;  media su 10\' in m/s', unit: 'm/s' },
		'gre000d0': { name: 'Radiazione globale;  media giornaliera', unit: 'W/m²' },
		'gre000h0': { name: 'Radiazione globale;  media oraria', unit: 'W/m²' },
		'gre000m0': { name: 'Radiazione globale;  media mensile', unit: 'W/m²' },
		'gre000y0': { name: 'Radiazione globale;  media annuale', unit: 'W/m²' },
		'gre000z0': { name: 'Radiazione globale;  media su 10\'', unit: 'W/m²' },
		'hto000d0': { name: 'Altezza della neve fresca;  somma giornaliera', unit: 'cm' },
		'hto000m0': { name: 'Altezza della neve fresca;  somma mensile', unit: 'cm' },
		'hto000y0': { name: 'Altezza della neve fresca;  somma annuale', unit: 'cm' },
		'htoautd0': { name: 'Altezza del manto nevoso (misurazione automatica);  misura delle 6 UTC', unit: 'cm' },
		'htoauths': { name: 'Altezza del manto nevoso (misurazione automatica);  valore momentaneo orario', unit: 'cm' },
		'htoauts0': { name: 'Altezza del manto nevoso (misurazione automatica);  valore momentaneo', unit: 'cm' },
		'nto000d0': { name: 'Copertura nuvolosa totale;  media giornaliera', unit: '%' },
		'nto000h0': { name: 'Copertura nuvolosa totale;  media oraria', unit: '%' },
		'nto000z0': { name: 'Copertura nuvolosa totale;  media su 10\'', unit: '%' },
		'ods000d0': { name: 'Radiazione diffusa;  media giornaliera', unit: 'W/m²' },
		'ods000h0': { name: 'Radiazione diffusa;  media oraria', unit: 'W/m²' },
		'ods000z0': { name: 'Radiazione diffusa;  media su 10\'', unit: 'W/m²' },
		'oli000d0': { name: 'Radiazione a onda lunga in ingresso;  media giornaliera', unit: 'W/m²' },
		'oli000h0': { name: 'Radiazione a onda lunga in ingresso;  media oraria', unit: 'W/m²' },
		'oli000m0': { name: 'Radiazione a onda lunga in ingresso;  media mensile', unit: 'W/m²' },
		'oli000y0': { name: 'Radiazione a onda lunga in ingresso;  media annuale', unit: 'W/m²' },
		'oli000z0': { name: 'Radiazione a onda lunga in ingresso;  media su 10\'', unit: 'W/m²' },
		'olo000d0': { name: 'Radiazione a onda lunga in uscita;  media giornaliera', unit: 'W/m²' },
		'olo000h0': { name: 'Radiazione a onda lunga in uscita;  media oraria', unit: 'W/m²' },
		'olo000m0': { name: 'Radiazione a onda lunga in uscita;  media mensile', unit: 'W/m²' },
		'olo000y0': { name: 'Radiazione a onda lunga in uscita;  media annuale', unit: 'W/m²' },
		'olo000z0': { name: 'Radiazione a onda lunga in uscita;  media su 10\'', unit: 'W/m²' },
		'osr000d0': { name: 'Radiazione a onda corta rilflessa;  media giornaliera', unit: 'W/m²' },
		'osr000h0': { name: 'Radiazione a onda corta rilflessa;  media oraria', unit: 'W/m²' },
		'osr000m0': { name: 'Radiazione a onda corta rilflessa;  media mensile', unit: 'W/m²' },
		'osr000y0': { name: 'Radiazione a onda corta rilflessa;  media annuale', unit: 'W/m²' },
		'osr000z0': { name: 'Radiazione a onda corta rilflessa;  media su 10\'', unit: 'W/m²' },
		'pp0qffd0': { name: 'Pressione ridotta al livello del mare (QFF);  media giornaliera', unit: 'hPa' },
		'pp0qffh0': { name: 'Pressione ridotta al livello del mare (QFF);  media oraria', unit: 'hPa' },
		'pp0qffm0': { name: 'Pressione ridotta al livello del mare (QFF);  media mensile', unit: 'hPa' },
		'pp0qffs0': { name: 'Pressione ridotta al livello del mare (QFF);  valore momentaneo', unit: 'hPa' },
		'pp0qffy0': { name: 'Pressione ridotta al livello del mare (QFF);  media annuale', unit: 'hPa' },
		'pp0qnhd0': { name: 'Pressione ridotta secondo l\'atmosfero standard (QNH);  media giornaliera', unit: 'hPa' },
		'pp0qnhh0': { name: 'Pressione ridotta secondo l\'atmosfero standard (QNH);  media oraria', unit: 'hPa' },
		'pp0qnhm0': { name: 'Pressione ridotta secondo l\'atmosfero standard (QNH);  media mensile', unit: 'hPa' },
		'pp0qnhs0': { name: 'Pressione ridotta secondo l\'atmosfero standard (QNH);  valore momentano', unit: 'hPa' },
		'pp0qnhy0': { name: 'Pressione ridotta secondo l\'atmosfero standard (QNH);  media annuale', unit: 'hPa' },
		'ppz700d0': { name: 'Altitudine geopotenziale del livello di 700 hPa;  media giornaliera', unit: 'gpm' },
		'ppz700h0': { name: 'Altitudine geopotenziale del livello di 700 hPa;  media oraria', unit: 'gpm' },
		'ppz700m0': { name: 'Altitudine geopotenziale del livello di 700 hPa;  media mensile', unit: 'gpm' },
		'ppz700s0': { name: 'Altitudine geopotenziale del livello di 700 hPa;  valore momentaneo', unit: 'gpm' },
		'ppz700y0': { name: 'Altitudine geopotenziale del livello di 700 hPa;  media annuale', unit: 'gpm' },
		'ppz850d0': { name: 'Altitudine geopotenziale del livello di 850 hPa;  media giornaliera', unit: 'gpm' },
		'ppz850h0': { name: 'Altitudine geopotenziale del livello di 850 hPa;  media oraria', unit: 'gpm' },
		'ppz850m0': { name: 'Altitudine geopotenziale del livello di 850 hPa;  media mensile', unit: 'gpm' },
		'ppz850s0': { name: 'Altitudine geopotenziale del livello di 850 hPa;  valore momentaneo', unit: 'gpm' },
		'ppz850y0': { name: 'Altitudine geopotenziale del livello di 850 hPa;  media annuale', unit: 'gpm' },
		'prestad0': { name: 'Pressione all\'altitudine barometrica (QFE);  media giornaliera', unit: 'hPa' },
		'prestah0': { name: 'Pressione all\'altitudine barometrica (QFE);  media oraria', unit: 'hPa' },
		'prestam0': { name: 'Pressione all\'altitudine barometrica (QFE);  media mensile', unit: 'hPa' },
		'prestas0': { name: 'Pressione all\'altitudine barometrica (QFE);  valore momentaneo', unit: 'hPa' },
		'prestay0': { name: 'Pressione all\'altitudine barometrica (QFE);  media annuale', unit: 'hPa' },
		'prestaz0': { name: 'Pressione al livello della stazione (QFE);  media su 10\'', unit: 'hPa' },
		'pva200d0': { name: 'Pressione del vapore acqueo a 2 m dal suolo;  media giornaliera', unit: 'hPa' },
		'pva200h0': { name: 'Pressione del vapore acqueo a 2 m dal suolo;  media oraria', unit: 'hPa' },
		'pva200m0': { name: 'Pressione del vapore acqueo a 2 m dal suolo;  media mensile', unit: 'hPa' },
		'pva200s0': { name: 'Pressione del vapore acqueo a 2 m dal suolo;  valore momentaneo', unit: 'hPa' },
		'pva200y0': { name: 'Pressione del vapore acqueo a 2 m dal suolo;  media annuale', unit: 'hPa' },
		'rdi000d0': { name: 'Radiazione diffusa;  media giornaliera', unit: 'W/m²' },
		'rdi000h0': { name: 'Radiazione diffusa;  media oraria', unit: 'W/m²' },
		'rdi000z0': { name: 'Radiazione diffusa;  media su 10\'', unit: 'W/m²' },
		'reference_timestamp': { name: 'Data/Ora', unit: '' }, 
		'rka150d0': { name: 'Precipitazioni;  somma giornaliera 0 UTC - 0 UTC', unit: 'mm' },
		'rre150d0': { name: 'Precipitazioni;  somma giornaliera', unit: 'mm' },
		'rre150h0': { name: 'Precipitazioni;  somma oraria', unit: 'mm' },
		'rre150m0': { name: 'Precipitazioni;  somma mensile', unit: 'mm' },
		'rre150y0': { name: 'Precipitazioni;  somma annuale', unit: 'mm' },
		'rre150z0': { name: 'Precipitazioni;  somma su 10\'', unit: 'mm' },
		'rreetsd0': { name: 'Registrazione idrica (bilancio idrico, R-ETS);  somma giornaliera', unit: 'mm' },
		'rreetsm0': { name: 'Registrazione idrica (bilancio idrico, R-ETS);  somma mensile', unit: 'mm' },
		'rreetsy0': { name: 'Registrazione idrica (bilancio idrico, R-ETS);  somma annuale', unit: 'mm' },
		'rsh150d0': { name: 'Ore di pioggia;  somma giornaliera', unit: 'h' },
		'rsh150m0': { name: 'Ore di pioggia;  somma mensile', unit: 'h' },
		'rsh150y0': { name: 'Ore di pioggia;  somma annuale', unit: 'h' },
		'rso150d0': { name: 'Ore di neve;  somma giornaliera', unit: 'h' },
		'rso150m0': { name: 'Ore di neve;  somma mensile', unit: 'h' },
		'rso150y0': { name: 'Ore di neve;  somma annuale', unit: 'h' },
		'sre000d0': { name: 'Soleggiamento;  somma giornaliera', unit: 'min' },
		'sre000h0': { name: 'Soleggiamento;  somma oraria', unit: 'min' },
		'sre000m0': { name: 'Soleggiamento;  somma mensile', unit: 'min' },
		'sre000y0': { name: 'Soleggiamento;  somma annuale', unit: 'min' },
		'sre000z0': { name: 'Soleggiamento;  somma su 10\'', unit: 'min' },
		'sremaxdv': { name: 'Soleggiamento;  rispetto al massimo giornaliero possibile', unit: '%' },
		'sremaxmv': { name: 'Soleggiamento;  somma mensile rispetto al massimo possibile', unit: '%' },
		'sremaxyv': { name: 'Soleggiamento;  somma annuale rispetto al massimo possibile', unit: '%' },
		'station_abbr': { name: 'Stazione', unit: '' }, 
		'stn': { name: 'Stazione', unit: '' }, 
		'tde200d0': { name: 'Temperatura di rugiada a 2 m dal suolo;  media giornaliera', unit: '°C' },
		'tde200h0': { name: 'Temperatura di rugiada a 2 m dal suolo;  media oraria', unit: '°C' },
		'tde200s0': { name: 'Punto di rugiada a 2 m dal suolo;  valore momentaneo', unit: '°C' },
		'tde200z0': { name: 'Temperatura di rugiada a 2 m dal suolo;  media su 10\'', unit: '°C' },
		'time': { name: 'Data/Ora', unit: '' }, 
		'tma200d0': { name: 'Temperatura dell\'aria a 2 m dal suolo;  massima giornaliera', unit: '°C' },
		'tmi200d0': { name: 'Temperatura dell\'aria a 2 m dal suolo;  minima giornaliera', unit: '°C' },
		'tre005d0': { name: 'Temperatura a 5 cm sull\'erba;  media giornaliera', unit: '°C' },
		'tre005dn': { name: 'Temperatura a 5 cm sull\'erba;  minima giornaliera', unit: '°C' },
		'tre005dx': { name: 'Temperatura a 5 cm sull\'erba;  massima giornaliera', unit: '°C' },
		'tre005h0': { name: 'Temperatura a 5 cm sull\'erba;  media oraria', unit: '°C' },
		'tre005hn': { name: 'Temperatura a 5 cm sull\'erba;  minima oraria', unit: '°C' },
		'tre005m0': { name: 'Temperatura a 5 cm sull\'erba;  media mensile', unit: '°C' },
		'tre005mn': { name: 'Temperatura a 5 cm sull\'erba;  minima mensile assoluta', unit: '°C' },
		'tre005mx': { name: 'Temperatura a 5 cm sull\'erba;  massima mensile assoluta', unit: '°C' },
		'tre005s0': { name: 'Temperatura a 5 cm sull\'erba;  valore momentaneo', unit: '°C' },
		'tre005y0': { name: 'Temperatura a 5 cm sull\'erba;  media annuale', unit: '°C' },
		'tre005yn': { name: 'Temperatura a 5 cm sull\'erba;  minima annuale assoluta', unit: '°C' },
		'tre005yx': { name: 'Temperatura a 5 cm sull\'erba;  massima annuale assoluta', unit: '°C' },
		'tre200d0': { name: 'Temperatura dell\'aria a 2 m dal suolo;  media giornaliera', unit: '°C' },
		'tre200d1': { name: 'Temperatura dell\'aria a 2 m dal suolo;  massima giornaliera', unit: '°C' },
		'tre200d2': { name: 'Temperatura dell\'aria a 2 m dal suolo;  minima giornaliera', unit: '°C' },
		'tre200dn': { name: 'Temperatura dell\'aria a 2 m dal suolo;  minima giornaliera', unit: '°C' },
		'tre200dx': { name: 'Temperatura dell\'aria a 2 m dal suolo;  massima giornaliera', unit: '°C' },
		'tre200h0': { name: 'Temperatura dell\'aria a 2 m dal suolo;  media oraria', unit: '°C' },
		'tre200hn': { name: 'Temperatura dell\'aria a 2 m dal suolo;  minima oraria', unit: '°C' },
		'tre200hx': { name: 'Temperatura dell\'aria a 2 m dal suolo;  massima oraria', unit: '°C' },
		'tre200m0': { name: 'Temperatura dell\'aria a 2 m dal suolo;  media mensile', unit: '°C' },
		'tre200mn': { name: 'Temperatura dell\'aria a 2 m dal suolo;  minima mensile assoluta', unit: '°C' },
		'tre200mx': { name: 'Temperatura dell\'aria a 2 m dal suolo;  massima mensile assoluta', unit: '°C' },
		'tre200s0': { name: 'Temperatura dell\'aria a 2 m dal suolo;  valore momentaneo', unit: '°C' },
		'tre200y0': { name: 'Temperatura dell\'aria a 2 m dal suolo;  media annuale', unit: '°C' },
		'tre200yn': { name: 'Temperatura dell\'aria a 2 m dal suolo;  minima annuale assoluta', unit: '°C' },
		'tre200yx': { name: 'Temperatura dell\'aria a 2 m dal suolo;  massima annuale assoluta', unit: '°C' },
		'tre200z0': { name: 'Temperatura dell\'aria a 2 m dal suolo;  media su 10\'', unit: '°C' },
		'tresurs0': { name: 'Temperatura dell\'aria al livello del suolo;  valore momentaneo', unit: '°C' },
		'ure200d0': { name: 'Umidità relativa dell\'aria a 2 m dal suolo;  media giornaliera', unit: '%' },
		'ure200h0': { name: 'Umidità relativa dell\'aria a 2 m dal suolo;  media oraria', unit: '%' },
		'ure200m0': { name: 'Umidità relativa dell\'aria a 2 m dal suolo;  media mensile', unit: '%' },
		'ure200s0': { name: 'Umidità relativa dell\'aria a 2 m dal suolo;  valore momentaneo', unit: '%' },
		'ure200y0': { name: 'Umidità relativa dell\'aria a 2 m dal suolo;  media annuale', unit: '%' },
		'ure200z0': { name: 'Umidità relativa dell\'aria a 2 m dal suolo;  media su 10\'', unit: '%' },
		'van200d0': { name: 'Tensione di vapore a 2 m dal suolo;  media giornaliera', unit: 'hPa' },
		'van200h0': { name: 'Tensione di vapore a 2 m dal suolo;  media oraria', unit: 'hPa' },
		'van200z0': { name: 'Tensione di vapore a 2 m dal suolo;  media su 10\'', unit: 'hPa' },
		'vof010d0': { name: 'Indice di favonio', unit: 'Code' },
		'wcc006d0': { name: 'Indice di favonio;  valore giornaliera', unit: 'min' },
		'wcc006h0': { name: 'Indice di favonio;  valore oraria', unit: 'min' },
		'wcc006s0': { name: 'Indice di favonio', unit: 'Code' }, 
		'xcd000d0': { name: 'Giorni di raffredamento (CDD)', unit: '°C' }, 
		'xcd000m0': { name: 'Giorni di raffredamento (CDD);  totale mensile', unit: '°C' },
		'xcd000y0': { name: 'Giorni di raffredamento (CDD);  somma annuale', unit: '°C' },
		'xchills0': { name: 'Temperatura fredda;  valore momentaneo', unit: '°C' },
		'xno000d0': { name: 'Gradi riscaldamento (12/20)', unit: '°C' }, 
		'xno000m0': { name: 'Gradi riscaldamento (12/20);  somma mensile', unit: '°C' },
		'xno000y0': { name: 'Gradi riscaldamento (12/20);  somma annuale', unit: '°C' },
		'xno012d0': { name: 'Gradi riscaldamento (ATD12/12)', unit: '°C' }, 
		'xno012m0': { name: 'Gradi riscaldamento (ATD12/12);  somma mensile', unit: '°C' },
		'xno012y0': { name: 'Gradi riscaldamento (ATD12/12);  somma annuale', unit: '°C' }
    }
};

// Immediately execute the function to define the coordinate systems for Proj4js.
// This ensures that the definitions are available as soon as the script is loaded.
METEO_CONFIG.initializeProj4Defs();

